### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by danielsalles** [wejs/we-plugin-passport-jwt#1]
```
added in package.json.dependencies: we-plugin-passport-jwt
we-plugin-passport-jwt added in package.json.wejs.plugins
running: npm install 
running: plugins install methods
/home/daniel/dev/tigerunn2/tigerunn/node_modules/we-plugin-passport-jwt/plugin.js:69
      throw new Error('passport-jwt:we.config.passport.strategies.jwt.secretOrKey config is required');
      ^

Error: passport-jwt:we.config.passport.strategies.jwt.secretOrKey config is required
    at EventEmitter.<anonymous> (/home/daniel/dev/tigerunn2/tigerunn/node_modules/we-plugin-passport-jwt/plugin.js:69:13)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at we.utils.async.eachSeries (/home/daniel/dev/tigerunn2/tigerunn/node_modules/we-core/src/bootstrapFunctions.js:49:19)
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:421:16
    at replenish (/home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:931:17)
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:906:16
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:3861:9
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:998:13)
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:906:16
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/async/dist/async.js:3858:13
    at fs.readdir (/home/daniel/dev/tigerunn2/tigerunn/node_modules/we-core/src/class/Plugin.js:389:7)
    at FSReqWrap.oncomplete (fs.js:135:15)
```

I believe it is a bug when installing without setting the environment.

**Comment by albertosouza** [comment]
Hi @danielsalles , Thanks for your feedback
This is the expected behavior. Once installed the system will only starts if secretOrKey configuration is populated. A security behavior
One possible improvement would be to generate random text and add this setting in the project when installing the plugin ... i will create an issue for this task.
