### ISSUE TITLE
"subject" must be a string

### ISSUE THREAD

**Issue by danielsalles** [wejs/we-plugin-passport-jwt#2]
```
ValidationError: child "subject" fails because ["subject" must be a string]
    at Object.exports.process (/home/daniel/dev/tigerunn2/tigerunn/node_modules/joi/lib/errors.js:140:17)
    at internals.Object.internals.Any.validate (/home/daniel/dev/tigerunn2/tigerunn/node_modules/joi/lib/any.js:667:25)
    at Object.module.exports [as sign] (/home/daniel/dev/tigerunn2/tigerunn/node_modules/jsonwebtoken/sign.js:101:47)
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/we-plugin-passport-jwt/server/controllers/passportJWT.js:49:27
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/bcryptjs/dist/bcrypt.js:297:21
    at /home/daniel/dev/tigerunn2/tigerunn/node_modules/bcryptjs/dist/bcrypt.js:1250:21
    at Immediate.next [as _onImmediate] (/home/daniel/dev/tigerunn2/tigerunn/node_modules/bcryptjs/dist/bcrypt.js:1130:21)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```
Subject ceases to be undefined, when set null. So gives this error.

**Comment by albertosouza** [comment]
Hello @danielsalles , Thanks for your feedback.
README.md example and configuration comments in plugin.js update to set undefined and skip this error.
More documentation about passport jwt is avalible in https://www.npmjs.com/package/passport-jwt  and https://www.npmjs.com/package/jsonwebtoken
